services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    
    volumes:
      - rabbitmq-data:/var/lib/data/rabbitmq/
      - rabbitmq-logs:/var/lib/logs/rabbitmq/

    networks:
      - ms_relatorio

    ports: 
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

networks:
  ms_relatorio:
    driver: bridge

volumes:
  rabbitmq-data:
  rabbitmq-logs: